### ISSUE TITLE
ImportError about  check_scoring

### ISSUE THREAD

**Issue by LIANGSNOW** [aerdem4/lofo-importance#18]
Hi,

I was running the example notebook, here came the problem :

from lofo.lofo_importance import LOFOImportance

~/Desktop/lofo-importance/lofo/flofo_importance.py in <module>()
      4 import multiprocessing
      5 import warnings
----> 6 from sklearn.metrics import check_scoring
      7 
      8 

ImportError: cannot import name 'check_scoring'

I found the latest version about sklearn is using  
'from sklearn.metrics.scorer import check_scoring'

**Comment by aerdem4** [comment]
If you are using the latest sklearn version, it shouldn't be a problem:
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/__init__.py#L69

I see that there is also a PR about it to make it work on sklearn < 0.20:
https://github.com/aerdem4/lofo-importance/pull/16
